name: linting, testing, building
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]
    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{matrix.node.version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - name: install modules
        run: npm install
      - name: build production project
        run: npm run build:prod
      - name: linting ts
        run: npm run lint:ts
      - name: linting style
        run: npm run lint:style
      - name: unit test
        run: npm run test:unit
